### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mljli** [mljli/maze#1]
- [ ] print game info such as fps, time, number of marks
- [ ] make wall taller, find a better texture
- [ ] add doors at entrance and exit, jail the player
- [ ] game over screen
- [ ] fixed lights/candles
- [ ] performance optimization
- [ ] menus, configuration, sound, ... (use SDL or something else)
- [ ] replace mark with footprint
